/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as AssetsSlugRouteImport } from './routes/assets/$slug'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSlugRoute = AssetsSlugRouteImport.update({
  id: '/assets/$slug',
  path: '/assets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$slug': typeof AssetsSlugRoute
  '/assets/': typeof AssetsIndexRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$slug': typeof AssetsSlugRoute
  '/assets': typeof AssetsIndexRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$slug': typeof AssetsSlugRoute
  '/assets/': typeof AssetsIndexRoute
  '/studio': typeof StudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assets/$slug' | '/assets/' | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assets/$slug' | '/assets' | '/studio'
  id: '__root__' | '/' | '/assets/$slug' | '/assets/' | '/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRoute
  IndexRoute: typeof IndexRoute
  AssetsSlugRoute: typeof AssetsSlugRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$slug': {
      id: '/assets/$slug'
      path: '/assets/$slug'
      fullPath: '/assets/$slug'
      preLoaderRoute: typeof AssetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRoute,
  IndexRoute: IndexRoute,
  AssetsSlugRoute: AssetsSlugRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
